program: experiment.py
method: bayes
metric:
  goal: minimize
  name: val_rmse_F

parameters:
  # Model architecture parameters
  model_size:
    values: ["tiny", "small", "medium", "large"]
  
  # Training parameters - FIXED: use proper wandb syntax
  learning_rate:
    values: [0.0001, 0.001, 0.01]
  
  batch_size:
    value: 2
  
  # Sequence lengths
  input_sequence_length:
    values: [3, 6]
  
  output_sequence_length:
    value: 1
  
  # Data filtering parameters
  max_input_nodata_pct:
    values: [0.0, 0.5, 1.0]    
  
  # Training constraints
  max_epochs:
    value: 10
  
  # Fixed parameters (not swept)
  gpus:
    value: 1
  precision:
    value: "16"
  num_workers:
    value: 8
  debug_monthly_split:
    value: true
  debug_year:
    value: 2014
  limit_train_batches:
    value: 0.3
  limit_val_batches:
    value: 0.3
  
  # Year splits
  train_years:
    value: [2013, 2014, 2015]
  val_years:
    value: [2016]
  test_years:
    value: [2016]